Repository Security-Tools-Alliance/rengine-ng, pull requests merged in 2024-08, with the labels that each got.

#126 fix(fetch_url): fix unwanted subdomain and rework fetch_url task
  default_yaml_config.yaml
  web/fixtures/default_scan_engines.yaml
  web/reNgine/common_func.py
  web/reNgine/settings.py
  web/reNgine/tasks.py
  web/scanEngine/templates/scanEngine/add_engine.html
Labels: bug

#135 build(ci): fix missing write permissions
  .github/workflows/release.yml
Labels: bug

#137 fix(docs): change art logo and fix doc link
  web/art/reNgine.txt
  web/scanEngine/templates/scanEngine/_items/form_engine.html
Labels: bug

#141 fix(cidr): add CIDR import
  web/api/views.py
  web/targetApp/templates/target/add.html
  web/targetApp/views.py
Labels: bug

#139 feat(install): add the prebuilt docker images to install
  .env
  .env-dist
  .gitignore
  .vscode/launch.json
  .vscode/tasks.json
  Makefile
  config/default_yaml_config.yaml
  docker-compose.dev.yml
  docker-compose.setup.yml
  docker/beat/entrypoint-dev.sh
  docker/celery/Dockerfile
  docker/celery/entrypoint-dev.sh
  docker/celery/entrypoint.sh
  docker/celery/pyproject.toml
  docker/certs/Dockerfile
  docker/certs/entrypoint.sh
  docker/docker-compose.build.yml
  docker/docker-compose.dev.yml
  docker/docker-compose.setup.yml
  docker/docker-compose.yml
  docker/ollama/Dockerfile
  docker/postgres/Dockerfile
  docker/proxy/Dockerfile
  docker/proxy/config/rengine.conf
  docker/redis/Dockerfile
  docker/web/Dockerfile
  docker/web/entrypoint-dev.sh
  docker/web/entrypoint.sh
  docker/web/pyproject.toml
  install.sh
  make.bat
  scripts/uninstall.sh
  scripts/update.sh
  update.sh
  web/Dockerfile
  web/dashboard/templates/dashboard/onboarding.html
  web/fixtures/external_tools.yaml
  web/reNgine/common_func.py
  web/reNgine/settings.py
  web/reNgine/version.txt
  web/requirements.txt
  web/scanEngine/templates/scanEngine/_items/form_engine.html
  web/scanEngine/views.py
  web/static/custom/toolbox.js
Labels: enhancement

#144 build(ci): add CI for closing issues when PR is merged
  .github/release.yml
  .github/workflows/build-pr.yml
  .github/workflows/build.yml
  .github/workflows/close-issues-on-pr-merge-to-release-branch.yml
Labels: ci

#145 fix(ui): restore static files path & remove beat entrypoint useless code
  docker/beat/entrypoint-dev.sh
  docker/docker-compose.yml
  docker/web/entrypoint-dev.sh
  docker/web/entrypoint.sh
Labels: bug

#147 fix(scan): subdomain import with suffix more than 4 chars
  web/reNgine/common_func.py
  web/reNgine/tasks.py
Labels: bug

#153 build(ci): extract issue number from PR body
  .github/workflows/close-issues-on-pr-merge-to-release-branch.yml
Labels: bug

#158 docs(readme): set badge to latest release automatically
  README.md
Labels: bug

#159 fix(readme): remove space after url
  README.md
Labels: bug

#161 build(docker): add ARM support for Celery Dockerfile
  docker/celery/Dockerfile
Labels: enhancement

#164 fix(ui): permit to link tab URL and history back into it
  web/static/assets/js/app.min.js
  web/static/custom/custom.js
  web/templates/base/base.html
Labels: bug

#167 docs(readme): remove note
  README.md
Labels: documentation

#171 fix(ui): load default yaml config on add scan engine form
  web/config/default_yaml_config.yaml
  web/scanEngine/templates/scanEngine/_items/form_engine.html
  web/scanEngine/templates/scanEngine/add_engine.html
  web/scanEngine/views.py
Labels: bug

#155 build(docker): improve makefile, docker verbosity & provide unit tests
  .env-dist
  .gitignore
  Makefile
  docker/celery/entrypoint.sh
  docker/docker-compose.yml
  docker/web/entrypoint-dev.sh
  install.sh
  scripts/common_functions.sh
  scripts/run_tests.sh
  scripts/uninstall.sh
  scripts/update.sh
  tests/test_makefile.py
Labels: enhancement

#169 fix(ui): tools settings page
  docker/celery/Dockerfile
  docker/celery/config/.gau.toml
  docker/celery/config/amass.ini
  docker/celery/config/the-harvester-api-keys.yaml
  docker/docker-compose.yml
  web/api/urls.py
  web/api/views.py
  web/reNgine/settings.py
  web/reNgine/tasks.py
  web/scanEngine/static/scanEngine/js/custom_tools.js
  web/scanEngine/templates/scanEngine/settings/tool.html
  web/scanEngine/views.py
  web/static/custom/custom.js
Labels: bug

#176 fix(oneforall): wrong s3 bucket reported
  web/reNgine/tasks.py
Labels: bug

#178 fix(ssl): add SAN extension to the cert
  docker/certs/entrypoint.sh
Labels: bug

#180 fix(ui): stored XSS
  web/startScan/static/startScan/js/detail_scan.js
  web/static/custom/custom.js
Labels: bug

#183 fix(install): revert changes of prebuilt chain
  install.sh
Labels: bug

#184 fix(ui): fix 500 error on scan engine add
  web/scanEngine/views.py
Labels: bug
