Repository Security-Tools-Alliance/rengine-ng, pull requests merged in 2024-06, with the labels that each got.

#90 refactor(scan): custom headers
  default_yaml_config.yaml
  web/reNgine/common_func.py
  web/reNgine/tasks.py
  web/scanEngine/templates/scanEngine/_items/form_engine.html
Labels: bug

#82 feat(install): arm64 support
  install.sh
  web/Dockerfile
Labels: enhancement

#92 fix(security): rework scan working folder location to prevent leaks
  web/reNgine/settings.py
  web/reNgine/tasks.py
  web/targetApp/views.py
Labels: bug

#94 fix(scan): fix bad base path retrieval for results dir
  web/reNgine/tasks.py
Labels: bug

#96 fix(scan): rework the alive endpoint and redirection operation
  README.md
  default_yaml_config.yaml
  web/dashboard/views.py
  web/reNgine/tasks.py
  web/startScan/models.py
  web/startScan/static/startScan/js/detail_scan.js
  web/startScan/views.py
  web/targetApp/views.py
Labels: bug

#68 dev(debug): complete dev environment to debug/code easily
  .vscode/launch.json
  Makefile
  README.md
  docker-compose.dev.yml
  docker-compose.yml
  install.sh
  make.bat
  web/beat-entrypoint-dev.sh
  web/celery-entrypoint-dev.sh
  web/celery-entrypoint.sh
  web/dashboard/urls.py
  web/debugger_setup.py
  web/entrypoint-dev.sh
  web/entrypoint.sh
  web/manage.py
  web/reNgine/settings.py
  web/reNgine/tasks.py
  web/tests/test_nmap.py
  web/tests/test_scan.py
Labels: enhancement

#100 fix(scan): check value returned for all subs saved
  web/reNgine/tasks.py
Labels: bug

#102 fix(scan): rework http_crawl to update subdomain datas
  web/reNgine/tasks.py
Labels: bug

#103 fix(ui): reset osint dork result id before display
  web/startScan/static/startScan/js/detail_scan.js
Labels: bug

#97 fix(scan): centralize and log subdomains creation
  web/reNgine/tasks.py
Labels: bug

#98 fix(tools): update git tools at startup
  web/celery-entrypoint.sh
Labels: bug

#84 ops(install): use python venv (pipx/poetry) to fix/prevent conflicting packages
  Makefile
  config/nginx/rengine.conf
  docker-compose.dev.yml
  docker-compose.yml
  docker/beat/entrypoint.sh
  docker/celery/Dockerfile
  docker/celery/cmseek-pyproject.toml
  docker/celery/ctfr-pyproject.toml
  docker/celery/entrypoint.sh
  docker/celery/eyewitness-pyproject.toml
  docker/celery/infoga-pyproject.toml
  docker/celery/oneforall-pyproject.toml
  docker/celery/pyproject.toml
  docker/web/Dockerfile
  docker/web/entrypoint.sh
  docker/web/pyproject.toml
  web/api/views.py
  web/beat-entrypoint.sh
  web/celery-entrypoint.sh
  web/entrypoint.sh
  web/reNgine/definitions.py
  web/reNgine/settings.py
  web/reNgine/tasks.py
  web/scanEngine/management/commands/dumpcustomengines.py
  web/scanEngine/management/commands/loadcustomengines.py
  web/scanEngine/views.py
  web/startScan/migrations/0057_alter_endpoint_techs.py
  web/startScan/views.py
  web/targetApp/views.py
Labels: enhancement

#113 fix(scan): add some iterable checks to prevent TypeError
  web/reNgine/common_func.py
  web/reNgine/tasks.py
Labels: bug

#114 fix(screenshot): get only some columns from csv file
  web/reNgine/common_func.py
  web/reNgine/tasks.py
Labels: bug

#109 docs: update expired Discord invitation link with non expiring one
  .github/CONTRIBUTING.md
  .github/workflows/auto-comment.yml
  README.md
Labels: documentation

#111 build(ci): automate releases based on tags and labels
  .github/release.yml
  .github/workflows/release.yml
Labels: enhancement

#118 fix(ui): escape vulnerability request/response in db and display in ui
  web/reNgine/tasks.py
  web/static/custom/custom.js
Labels: bug

#95 build(install/uninstall/update): improve usability, readability and overall user experience of output
  docker-compose.yml
  install.sh
  make.bat
  scripts/uninstall.sh
  update.sh
  web/api/views.py
  web/art/reNgine.txt
  web/scanEngine/forms.py
  web/templates/base/login.html
  web/templates/base/logout.html
  web/templates/report/template.html
Labels: enhancement
