Repository Security-Tools-Alliance/rengine-ng, pull requests merged in 2024-09, with the labels that each got.

#185 docs(readme): redirect install & update section to the wiki pages
  README.md
Labels: documentation

#151 build(ci): build docker images for each tag, release, push
  .github/workflows/build.yml
  .vscode/tasks.json
Labels: ci

#186 build(install): improve root detection and set ownership on files
  .env-dist
  install.sh
  make.bat
Labels: bug

#193 build(images): restrict image creation, add correct tags and clean non tagged images
  .github/workflows/build.yml
  .github/workflows/delete-untagged-images.yml
Labels: ci

#182 fix(scan): fix clocked and scheduled scan not working
  web/reNgine/common_func.py
  web/reNgine/settings.py
  web/reNgine/tasks.py
  web/startScan/templates/startScan/schedule_scan_list.html
  web/startScan/templates/startScan/schedule_scan_ui.html
  web/startScan/views.py
Labels: bug

#188 fix(graph): de-duplicate dorks and vulnerabilities
  web/api/serializers.py
  web/api/views.py
  web/static/custom/mitch.js
Labels: bug

#194 build(ci): improve CodeQL configuration
  .github/workflows/codeql-analysis.yml
Labels: ci

#196 dev(django): install django extensions to have more commands
  docker/celery/pyproject.toml
  docker/web/pyproject.toml
  web/reNgine/settings.py
Labels: enhancement

#199 build(docker): replace staticfiles volume to prevent empty directory
  docker/docker-compose.yml
Labels: bug

#200 feat(ui): disable update button in tool arsenal
  web/scanEngine/templates/scanEngine/settings/tool_arsenal.html
Labels: enhancement

#198 feat(todo): enhance todo functionality and error handling
  web/api/views.py
  web/recon_note/static/note/js/todo.js
  web/recon_note/templates/note/index.html
  web/recon_note/tests/test_recon_note.py
  web/recon_note/views.py
  web/startScan/static/startScan/js/detail_scan.js
  web/startScan/templates/startScan/detail_scan.html
  web/startScan/templates/startScan/subdomains.html
  web/static/assets/js/vendor.min.js
  web/static/custom/custom.css
  web/static/custom/todo.js
  web/static/plugins/snackbar/snackbar.min.js
  web/static/plugins/todo/todolist.css
  web/targetApp/templates/target/summary.html
  web/templates/base/_items/recon_note_modal.html
  web/templates/base/_items/top_nav.html
Labels: enhancement

#172 fix(custom_header): not correctly parsing parameters
  web/reNgine/common_func.py
  web/reNgine/tasks.py
  web/scanEngine/views.py
Labels: bug

#201 fix: change install_type value in .env-dist and add missing imports
  .env-dist
  web/reNgine/common_func.py
Labels: bug

#168 feat(ui): bulk remove vulnerabilities
  web/startScan/templates/startScan/detail_scan.html
  web/startScan/templates/startScan/vulnerabilities.html
  web/static/custom/custom.css
  web/static/custom/custom.js
  web/targetApp/templates/target/summary.html
  web/templates/base/_items/vulnerability_tab_content.html
Labels: enhancement

#209 refactor: improve robustness of nuclei result parsing
  web/reNgine/tasks.py
Labels: refactor

#206 refactor: replace hardcoded API URLs with dynamic endpoint URLs
  web/api/views.py
  web/dashboard/templates/dashboard/index.html
  web/scanEngine/templates/scanEngine/settings/rengine.html
  web/startScan/static/startScan/js/detail_scan.js
  web/startScan/templates/startScan/detail_scan.html
  web/startScan/templates/startScan/endpoints.html
  web/startScan/templates/startScan/history.html
  web/startScan/templates/startScan/schedule_scan_list.html
  web/startScan/templates/startScan/subdomains.html
  web/startScan/templates/startScan/subscan_history.html
  web/startScan/templates/startScan/vulnerabilities.html
  web/startScan/views.py
  web/static/bootstrap/bootstrap.min.css
  web/static/custom/custom.js
  web/static/custom/right_sidebar.js
  web/static/custom/todo.js
  web/static/custom/toolbox.js
  web/targetApp/templates/target/add.html
  web/targetApp/templates/target/list.html
  web/targetApp/templates/target/summary.html
  web/templates/base/_items/right_bar.html
  web/templates/base/_items/top_bar.html
  web/templates/base/_items/widgets/vulnerability_highlights.html
  web/templates/base/base.html
Labels: bug, refactor

#210 refactor: update modal handling and improve CMS detection
  web/recon_note/templates/note/index.html
  web/scanEngine/static/scanEngine/js/custom_tools.js
  web/scanEngine/templates/scanEngine/settings/llm_toolkit.html
  web/startScan/static/startScan/js/detail_scan.js
  web/startScan/templates/startScan/detail_scan.html
  web/startScan/templates/startScan/subdomains.html
  web/static/custom/custom.js
  web/static/custom/todo.js
  web/static/custom/toolbox.js
  web/static/plugins/datatable/datatables.js
  web/static/plugins/todo/todolist.css
  web/targetApp/templates/organization/list.html
  web/targetApp/templates/target/summary.html
  web/templates/base/_items/modal.html
  web/templates/base/_items/top_bar.html
Labels: bug, refactor
