Repository Security-Tools-Alliance/rengine-ng, pull requests merged in 2025-08, with the labels that each got.

#294 build(ci): close all linked issues on PR merge to release branch
  .github/workflows/close-issues-on-pr-merge-to-release-branch.yml
Labels: ci

#295 build(ci): update release notes body in workflow and add changelog for previous versions
  .github/workflows/release.yml
  CHANGELOG.md
Labels: ci

#304 fix(llm): improve error detection and unify model selection
  web/api/views.py
  web/reNgine/llm/llm.py
  web/reNgine/llm/utils.py
  web/reNgine/tasks/llm.py
  web/startScan/templates/startScan/detail_scan.html
  web/static/custom/custom.js
Labels: bug

#300 fix: improve endpoint table column alignment and screenshot modal handling
  web/startScan/static/startScan/js/detail_scan.js
  web/startScan/templates/startScan/endpoints.html
  web/static/custom/custom.css
  web/static/custom/custom.js
  web/static/custom/port_display.js
  web/static/custom/right_sidebar.js
  web/templates/base/_items/endpoint_tab_content.html
Labels: bug

#322 release(changelog): correct changelog format for version 2.1.0 and later
  CHANGELOG.md
Labels: documentation

#324 fix(ui): update get_technologies to accept subdomain endpoint and update usage
  web/startScan/templates/startScan/detail_scan.html
  web/static/custom/custom.js
  web/static/custom/port_display.js
  web/targetApp/templates/target/summary.html
Labels: bug

#326 fix(celery): add isolated task context for thread safety and context management
  web/reNgine/celery_custom_task.py
  web/reNgine/tasks/fuzzing.py
Labels: bug

#330 fix(api): use scan id instead of object & fix queryset prefetching error
  web/api/views.py
Labels: bug

#311 fix: resolve `DirectoryFile` race condition in parallel fuzzing
  web/reNgine/settings.py
  web/reNgine/tasks/fuzzing.py
  web/reNgine/utilities/database.py
  web/reNgine/utilities/distributed_lock.py
  web/startScan/migrations/0068_auto_20250824_2131.py
  web/startScan/models.py
  web/tests/test_scan.py
  web/utils/test_utils.py
Labels: bug

#332 docs(release): add checkbox for modifying changelog
  CHANGELOG.md
  RELEASE.md
Labels: documentation
